version: '3'

services:

  init:
    env_file:
      - .env
    build:
      context: .
      dockerfile: init.Dockerfile
    volumes:
      - ./backstage:/app
      - /var/run/docker.sock:/var/run/docker.sock
