version: '3'

services:

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "7007:443"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backstage

  backstage:
    env_file:
      - .env
    build:
      context: .
      dockerfile: prod.Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      BACKEND_SECRET: ${BACKEND_SECRET}
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - backstage_pgdata:/var/lib/postgresql/data

volumes:
  backstage_pgdata:
